### ISSUE TITLE
Wrap around movements and show error if list is empty

### ISSUE THREAD

**Issue by sblask** [inkarkat/vim-QuickFixCurrentNumber#1]
**Motivation**

I currently have this in my config:

```
function! JumpInList(move, backup) abort
    try
        execute a:move
    catch /E553/ " reached end of list
        execute a:backup
    catch /E42/
        echohl WarningMsg
        echo 'Nothing in list'
        echohl None
    endtry
endfunction

nmap [q :call JumpInList('cprev', 'clast')<CR>
nmap ]q :call JumpInList('cnext', 'cfirst')<CR>

nmap [l :call JumpInList('lprev', 'llast')<CR>
nmap ]l :call JumpInList('lnext', 'lfirst')<CR>
```

So calling next on the last item goes back to the first item and vice versa. If the list is empty I show an error. I thought I can replace the native calls with calls to https://github.com/inkarkat/vim-QuickFixCurrentNumber so I get the same behaviour on the first and last item but otherwise jump relative to the current cursor position:

```
nmap [q :call JumpInList("normal \<Plug>(QuickFixCurrentNumberQPrev)", "normal \<Plug>(QuickFixCurrentNumberQLast)")<CR>
nmap ]q :call JumpInList("normal \<Plug>(QuickFixCurrentNumberQNext)", "normal \<Plug>(QuickFixCurrentNumberQFirst)")<CR>

nmap [l :call JumpInList("normal \<Plug>(QuickFixCurrentNumberLPrev)", "normal \<Plug>(QuickFixCurrentNumberLLast)")<CR>
nmap ]l :call JumpInList("normal \<Plug>(QuickFixCurrentNumberLNext)", "normal \<Plug>QuickFixCurrentNumberLFirst")<CR>
```

But it doesn't work because I don't get any errors on the first and last item or if there is nothing in the list.

**Request and Purpose**

It would be great if either the plugin would provide what I want (wrap around movements and error if no items) or if the commands would behave like the vim commands cprev/cnext and lprev/lnext and throw errors that I can catch and implement the behaviour myself. I am not sure whether the error handling on `execute "normal \<Plug>(QuickFixCurrentNumberLPrev)"` would be the same as `execute lnext` though. If it is, then it could probably be implemented with `!` like you have for Cgo/Lgo

**Comment by inkarkat** [comment]
Wrapping around makes a lot of sense for searches, but I'm not convinced that every iteration should do that by default.

However, the plugin allows to implement wrap-around; the trick is to not trigger the `<Plug>`-mappings directly, but the underlying functions (i.e. `QuickFixCurrentNumber#Next()` and `QuickFixCurrentNumber#Border()`); these indicate through their returned flag whether the navigation was successful or not. In the latter case, the plugin issues a beep and additionally for invocation errors (like when already inside the quickfix window) an error message. Like the original `<Plug>`-mappings, that error message can be queried via `ingo#err#IsSet()` to differentiate between them. (You could have `:catch`ed the error message issued by `:echoerr` by modifying the pattern, but the beep unfortunately cannot be captured - that's why you need to invoke the functions directly to get the flag.)

Your function just needs to be rewritten a bit:

    function! JumpInList( count, isLocationList, isBackward ) abort
        if ! QuickFixCurrentNumber#Next(a:count, a:isLocationList, a:isBackward) &&
        \   ! QuickFixCurrentNumber#Border(a:count, a:isLocationList, a:isBackward)
            if ingo#err#IsSet()
                call ingo#msg#ErrorMsg(ingo#err#Get())
            else
                call ingo#msg#WarningMsg('Nothing in list')
            endif
        endif
    endfunction

    nnoremap <silent> ]q :<C-u>call JumpInList(v:count1, 0, 0)<CR>
    nnoremap <silent> [q :<C-u>call JumpInList(v:count1, 0, 1)<CR>
    nnoremap <silent> ]l :<C-u>call JumpInList(v:count1, 1, 0)<CR>
    nnoremap <silent> [l :<C-u>call JumpInList(v:count1, 1, 1)<CR>

I hope this helps. If other people are interested in this, please comment here - I might then include this as an option directly into the plugin.

**Comment by sblask** [comment]
Awesome, thank you!
